
name: 'data_pipeline'
version: '0.1'
profile: 'data-pipeline'
config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"


models:
  
  
  data_pipeline: 
      staging: 
        +schema: stg
        +materialized: table
      # staging2: 
      #   +schema: stg2
      data-pipeline:
        materialized: table
        staging:
          materialized: view
        


  snapshots:
    target_schema: snapshots
